name: flutter_mvi
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.27.4

dev_dependencies:
  test: 1.21.4
  mockito: 5.2.0
  build_runner: 2.2.0

