name: flutter_mvi
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: '>=3.3.9'

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.27.7

dev_dependencies:
  test: 1.22.1
  mockito: 5.3.2
  build_runner: 2.3.2

